Fix cannot build Docker images using Podman Compose
This PR resolves the following error when using `podman-compose`:

    Error: short-name "caddy:2.6.4-alpine" did not resolve to an alias and
    no unqualified-search registries are defined in
    "/etc/containers/registries.conf"

We also bump the Docker image for Caddy and Alpine Linux.